# Prompt
# Which is equivalent to

[line_break]
disabled = false

format = '$all'


# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'

#[username]
#style_user = 'white bold'
#style_root = 'black bold'
#format = '[$user]($style)'
#disabled = false
#show_always = true
#aliases = { "corpuser034g" = "matchai" }

#[hostname]
#ssh_only = false
#format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
#trim_at = '.companyname.com'
#disabled = false

[sudo]
disabled = false
symbol = "󱦚"
format = '[as $symbol ]($style)'

[package]
disabled = true

[time]
disabled = false

[cmd_duration]
min_time = 500
show_milliseconds = false
format = 'took [$duration](bold yellow)'

[direnv]
disabled = false

[directory]
read_only = ' 󰏮 '
#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = "󰝚 "
#"Pictures" = " "
#"Projects" = "󰲋 "

#[git_metrics]
#disabled =false

[c]
symbol = ""
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = ""
#style = "bg:#86BBD8"
format = 'via [ $symbol ($version) ]($style)'
recursive = true

[java]
symbol = ""
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = ""
format = '[ $symbol ($version) ]($style)'
